---
- name: Find and disable inactive accounts
  ansible.builtin.shell: |
    for user in $(awk -F: '$7 ~ /^\/sbin\/nologin/ { print $1 }' /etc/passwd); do
      usermod -L $user
    done
  # Désactive les comptes utilisateurs qui ont /sbin/nologin comme shell