---

- name: Set password expiration to 90 days
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS   90'
  # Définit l'expiration des mots de passe à 90 jours

- name: Set minimum password length to 12 characters
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^minlen'
    line: 'minlen = 12'
  # Définit la longueur minimale du mot de passe à 12 caractères
